# Generated by Django 6.1.1 on 2026-09-21 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="student",
            old_name="course",
            new_name="branch",
        ),
        migrations.AddField(
            model_name="student",
            name="phone",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="section",
            field=models.CharField(default="A", max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="student",
            name="semester",
            field=models.CharField(default="1", max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="student",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
