# Generated by Django 6.1.1 on 2026-09-23 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_rename_course_student_branch_student_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='face_image',
            field=models.ImageField(blank=True, null=True, upload_to='faces/'),
        ),
    ]
