# Generated by Django 6.1.1 on 2026-09-25 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_student_face_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='face_image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
