# Generated by Django 6.1.1 on 2026-09-26 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='face_embedding',
            field=models.TextField(blank=True, null=True),
        ),
    ]
