# Generated by Codex on 2026-10-05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0007_attendance_unique_student_attendance_per_day"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="attendance",
            name="unique_student_attendance_per_day",
        ),
        migrations.AddField(
            model_name="attendance",
            name="lecture_number",
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddConstraint(
            model_name="attendance",
            constraint=models.UniqueConstraint(
                fields=("student", "date", "lecture_number"),
                name="unique_student_attendance_per_lecture",
            ),
        ),
    ]
