# Generated by Codex on 2026-10-05

import datetime

from django.db import migrations, models
import django.db.models.deletion
from django.utils import timezone


def migrate_existing_attendance(apps, schema_editor):
    Attendance = apps.get_model("attendance", "Attendance")
    Lecture = apps.get_model("attendance", "Lecture")

    for attendance in Attendance.objects.select_related("student").all():
        subject = f"Lecture {attendance.lecture_number}"
        section = attendance.student.section or "General"
        start_time = attendance.time

        end_dt = (
            datetime.datetime.combine(attendance.date, attendance.time)
            + datetime.timedelta(hours=1)
        )
        end_time = end_dt.time()

        lecture, _created = Lecture.objects.get_or_create(
            subject=subject,
            section=section,
            date=attendance.date,
            start_time=start_time,
            end_time=end_time,
            defaults={
                "created_by": "System",
            },
        )

        marked_at = timezone.make_aware(
            datetime.datetime.combine(
                attendance.date,
                attendance.time,
            )
        )

        attendance.lecture = lecture
        attendance.marked_at = marked_at
        attendance.save(
            update_fields=[
                "lecture",
                "marked_at",
            ]
        )


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0008_attendance_lecture_number"),
    ]

    operations = [
        migrations.CreateModel(
            name="Lecture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject", models.CharField(max_length=100)),
                ("section", models.CharField(max_length=50)),
                ("date", models.DateField()),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                (
                    "created_by",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name="lecture",
            constraint=models.UniqueConstraint(
                fields=(
                    "subject",
                    "section",
                    "date",
                    "start_time",
                    "end_time",
                ),
                name="unique_lecture_slot",
            ),
        ),
        migrations.AddField(
            model_name="attendance",
            name="lecture",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendance_records",
                to="attendance.lecture",
            ),
        ),
        migrations.AddField(
            model_name="attendance",
            name="marked_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.RunPython(
            migrate_existing_attendance,
            migrations.RunPython.noop,
        ),
        migrations.RemoveConstraint(
            model_name="attendance",
            name="unique_student_attendance_per_lecture",
        ),
        migrations.RemoveField(
            model_name="attendance",
            name="date",
        ),
        migrations.RemoveField(
            model_name="attendance",
            name="lecture_number",
        ),
        migrations.RemoveField(
            model_name="attendance",
            name="time",
        ),
        migrations.AlterField(
            model_name="attendance",
            name="lecture",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendance_records",
                to="attendance.lecture",
            ),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="marked_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddConstraint(
            model_name="attendance",
            constraint=models.UniqueConstraint(
                fields=("student", "lecture"),
                name="unique_student_attendance_per_lecture",
            ),
        ),
    ]
