# Generated by Django 6.1.1 on 2026-10-05 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0012_leave_subject_leave_time_slot_timetable'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='teacher_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
